# Generated by Django 5.0.6 on 2025-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img2',
            field=models.ImageField(default='none', upload_to='pics'),
            preserve_default=False,
        ),
    ]
