# Generated by Django 5.1.7 on 2025-05-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Utrip", "0002_remove_reviews_blog_remove_reviews_user_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
    ]
