# Generated by Django 5.0.6 on 2025-01-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0002_destination_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Gilgit-Baltistan', 'Gilgit-Baltistan')], max_length=30),
        ),
    ]
