# Generated by Django 5.0.6 on 2025-03-16 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0007_alter_profile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('offroader', 'Offroader'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('hybrid', 'Hybrid')], default='sedan', max_length=50)),
                ('registeration_number', models.CharField(max_length=20)),
                ('average_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='pics_vehicle')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='pics_vehicle')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utrip.city')),
            ],
        ),
        migrations.CreateModel(
            name='TripProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('destination', models.ManyToManyField(related_name='trip_proposals', to='Utrip.destination')),
                ('invitees', models.ManyToManyField(related_name='trip_invites', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField(default=1)),
                ('contact', models.IntegerField()),
                ('map', models.URLField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='pics_rooms')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='pics_rooms')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utrip.city')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utrip.type')),
            ],
        ),
    ]
