# Generated by Django 5.0.6 on 2025-03-17 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0009_alter_accommodation_img1_alter_accommodation_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='business_license',
            field=models.FileField(default='none', upload_to='documents/business_licenses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='owner',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='registration_certificate',
            field=models.FileField(default='none', upload_to='documents/registration_certificates/'),
            preserve_default=False,
        ),
    ]
