# Generated by Django 5.0.6 on 2025-03-17 19:28

import django.core.validators
import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0010_accommodation_address_accommodation_business_license_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/pics_rooms/'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/pics_rooms/'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='map',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
