# Generated by Django 5.0.6 on 2025-03-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0011_alter_accommodation_contact_alter_accommodation_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='map',
        ),
    ]
