"""
Django settings for trip_planning project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-*!3qfub#tpbpamgmu3a2@_i*d#5cj+t8#x89gcnp(rjls%g!=x'

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My external apps
    'Utrip',
    'social_django',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'location_field.apps.DefaultConfig',
]

# Required settings:
LOCATION_FIELD = {
    'map.provider': 'google',  
    'map.zoom': 10,
    'search.provider': 'google',  
    'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
    'provider.google.api_key': 'AIzaSyDfHPn_g2tKWKAnb4YVJy-Q0mKYL_7D3_Q',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware"
]


SOCIALACCOUNT_PROVIDERS= {
    'google' : {
        'APP':{
            'client_id': '611068490642-fq0kn0mjevl0ijmgerul8gd36d83va40.apps.googleusercontent.com',
            'secret': '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',
            'key':''
        }
    }
}
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'index'
ACCOUNT_LOGOUT_REDIRECT_URL = 'index'
ROOT_URLCONF = 'trip_planning.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Add any other context processors you may need
            ],
        },
    },
]


WSGI_APPLICATION = 'trip_planning.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
SITE_ID = 1
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Corrected STATIC_URL with a trailing slash
# settings.py

STATIC_URL = '/static/'

# Add this line
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Ensure STATICFILES_DIRS is defined correctly
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Only if you have a 'static' folder
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# to receive messages from user
# as we are still working locally so no need for SMTP setup we will review this later
# settings.py

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'travellmaatte@gmail.com'
EMAIL_HOST_PASSWORD = 'tjot qopy cknh efsb'
DEFAULT_FROM_EMAIL = 'travellmaatte@gmail.com'
EMAIL_TIMEOUT = 160  # 60 seconds
EMAIL_USE_LOCALTIME = False
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
SERVER_EMAIL ='travellmaatte@gmail.com'

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Default Django authentication

]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# settings.py
MEDIA_URL = '/media/'
