# Generated by Django 5.0.6 on 2025-02-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reviews_blog_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
