# Generated by Django 5.0.6 on 2025-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reviews_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/pics_blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img1',
            field=models.ImageField(upload_to='pictures/pics_blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img2',
            field=models.ImageField(upload_to='pictures/pics_blog'),
        ),
    ]
