# Generated by Django 5.0.6 on 2025-01-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField(default=1)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='pics_rooms')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='pics_rooms')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='pics_vehicle')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='pics_vehicle')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.destination')),
            ],
        ),
    ]
