# Generated by Django 5.0.6 on 2025-02-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utrip', '0004_profile'),
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utrip.city'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utrip.city'),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
