# Generated by Django 5.0.6 on 2025-02-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_alter_transportation_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.type'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimation.type'),
        ),
    ]
