# Generated by Django 5.0.6 on 2025-02-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_type_alter_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='map',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
