# Generated by Django 5.0.6 on 2025-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_accommodation_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='destination',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('sUV', 'SUV'), ('offroader', 'Offroader'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('hybrid', 'Hybrid')], default='sedan', max_length=50),
        ),
    ]
