# Generated by Django 5.0.6 on 2025-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_rename_destination_transportation_origin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='average_price',
            new_name='average_rent',
        ),
        migrations.AddField(
            model_name='transportation',
            name='registeration_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
