# Generated by Django 5.0.6 on 2025-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_rename_average_price_transportation_average_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('offroader', 'Offroader'), ('hatchback', 'Hatchback'), ('crossover', 'Crossover'), ('hybrid', 'Hybrid')], default='sedan', max_length=50),
        ),
    ]
